title: Welcome to my Developer Landing Page!
author: Isfaaq
email: isfaaqg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Isfaaq Goomany's Github page.

# social links
twitter_username: @_Isfaaq_
github_username:  Isfaaq

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
